/* Excel import runs locally. Only mapped surveillance fields are saved. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]/g,''),blank=v=>v==null||String(v).trim()==='';
 const fields=[
 ['id','Case ID',['caseid','id']],['year','Year',['year','reportingyear']],['mw','Morbidity week',['mw','morbidityweek','week']],
 ['onset','Date of onset',['onset','donset','dateofonset','dateonsetofillnessfirstsymptoms']],['sex','Sex',['sex','gender']],['age','Age in years',['age','ageyears','ageinyears']],
 ['classification','Case classification',['classification','caseclassification']],['outcome','Outcome',['outcome']],['barangay','Barangay',['barangay','currentaddressbarangay','brgy']],
 ['city','City / municipality',['city','municipality','currentaddresscitymunicipality','muncity']],['province','Province',['province','currentaddressprovince']],
 ['labResult','Laboratory result',['labresult','laboratoryresult','labres']],['testType','Test conducted',['testtype','typeoftestconducted','labtest']],
 ['clinicalCategory','Dengue clinical category',['clinicalcategory','clinicalclassification','clinclass']],['exposure','Lepto exposure',['exposure']],
 ['exposurePlace','Lepto place of exposure',['exposureplace','placeexposurecitymunicipality','placeexposurecitymun']],['disease','Disease (if present)',['disease']]
 ];
 const button=document.createElement('button');button.type='button';button.className='btn';button.id='batchUpload';button.textContent='Batch upload';$('#addCase').before(button);
 const modal=document.createElement('div');modal.className='modal';modal.id='batchModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','batchTitle');
 modal.innerHTML=`<div class="modal-card batch-card"><div class="modal-head"><div><h3 id="batchTitle">Batch upload</h3><p>Import Excel records into the selected disease registry.</p></div><button class="close" id="batchClose" aria-label="Close batch upload">×</button></div><div class="batch-body"><p class="callout">Choose a worksheet, review the counts, then import. Existing cases are kept; matching Case IDs are skipped. Files and new records stay in this browser.</p><div class="batch-controls"><div class="field"><label for="batchFile">EXCEL FILE</label><input id="batchFile" type="file" accept=".xlsx,.xls,.csv"></div><button class="btn" id="batchTemplate">Download Excel template</button><div class="field"><label for="batchSheet">WORKSHEET</label><select id="batchSheet" disabled></select></div><div class="field"><label for="batchYear">YEAR FOR ROWS WITHOUT A YEAR</label><input id="batchYear" type="number" min="1900" max="2100"></div></div><p id="batchStatus" role="status" aria-live="polite">Select an Excel file (.xlsx or .xls), or CSV. Maximum 25 MB.</p><details id="batchMapping" hidden><summary>Column mapping</summary><p>Match your headers to the fields below. Unmapped names, birth dates and street addresses are not imported.</p><div class="batch-mapping-grid" id="batchFields"></div><button class="btn" id="batchApplyMapping">Refresh preview</button></details><div id="batchPreview"></div><div class="form-actions"><button class="btn" id="batchCancel">Cancel</button><button class="btn primary" id="batchCommit" disabled>Import valid records</button></div></div></div>`;
 document.body.append(modal);
 let workbook=null,matrix=[],headerIndex=-1,mapping={},pending=[],context=null,sequence=0;
 const status=message=>{$('#batchStatus').textContent=message;};
 function reset(){workbook=null;matrix=[];pending=[];$('#batchFile').value='';$('#batchSheet').innerHTML='';$('#batchSheet').disabled=true;$('#batchMapping').hidden=true;$('#batchPreview').innerHTML='';$('#batchCommit').disabled=true;}
 function close(){sequence++;modal.classList.remove('open');reset();button.focus();}
 button.onclick=()=>{sequence++;reset();context=window.SurveillanceBatch.context();$('#batchTitle').textContent=`Batch upload · ${context.disease==='dengue'?'Dengue':'Leptospirosis'}`;$('#batchYear').value=context.year;status('Select an Excel file (.xlsx or .xls), or CSV. Maximum 25 MB.');modal.classList.add('open');$('#batchFile').focus();};
 $('#batchClose').onclick=$('#batchCancel').onclick=close;
 modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const nodes=[...modal.querySelectorAll('button,input,select,summary')].filter(n=>!n.disabled&&n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus();}}});
 function detect(rows){for(let i=0;i<Math.min(40,rows.length);i++){const h=rows[i].map(norm),has=k=>fields.find(f=>f[0]===k)[2].some(a=>h.includes(a));if(has('id')&&has('age')&&(has('mw')||has('classification')))return i;}return -1;}
 function sheetRows(name){const sheet=workbook.Sheets[name];if(sheet['!ref']){const range=XLSX.utils.decode_range(sheet['!ref']);if(range.e.r>50000||range.e.c>300)throw Error('This worksheet exceeds 50,000 rows or 300 columns. Split it into smaller files.');}return XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true,blankrows:true});}
 $('#batchFile').onchange=async()=>{const seq=++sequence;pending=[];$('#batchCommit').disabled=true;$('#batchPreview').innerHTML='';$('#batchMapping').hidden=true;$('#batchSheet').disabled=true;workbook=null;const file=$('#batchFile').files[0];if(!file)return;
 try{if(!/\.(xlsx|xls|csv)$/i.test(file.name))throw Error('Choose an .xlsx, .xls or .csv file.');if(file.size>25*1024*1024)throw Error('Maximum file size is 25 MB.');status('Reading workbook…');const buffer=await file.arrayBuffer();if(seq!==sequence)return;workbook=XLSX.read(buffer,{type:'array',cellDates:false,cellFormula:false,cellHTML:false,bookVBA:false});const usable=[];for(const name of workbook.SheetNames){try{const rows=sheetRows(name);if(detect(rows)>=0)usable.push(name);}catch{}}
 if(!usable.length)throw Error('No case worksheet found. Include Case ID, Age and Morbidity Week or Case Classification headers in the first 40 rows. You can use the Excel template.');
 $('#batchSheet').innerHTML=usable.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');$('#batchSheet').disabled=false;$('#batchSheet').value=usable.includes(String(context.year))?String(context.year):usable[0];await selectSheet();
 }catch(e){if(seq===sequence){workbook=null;$('#batchSheet').innerHTML='';status('Could not read file: '+e.message);}}};
 async function selectSheet(){try{matrix=sheetRows($('#batchSheet').value);headerIndex=detect(matrix);if(headerIndex<0)throw Error('Case headers could not be found.');const headers=matrix[headerIndex];mapping={};fields.forEach(([key,,aliases])=>{mapping[key]=headers.findIndex(h=>aliases.includes(norm(h)));});const yearMatch=$('#batchSheet').value.match(/(?:^|\D)((?:19|20)\d{2})(?:\D|$)/);$('#batchYear').value=yearMatch?yearMatch[1]:context.year;
 $('#batchFields').innerHTML=fields.filter(([key])=>context.disease==='dengue'?!['exposure','exposurePlace'].includes(key):key!=='clinicalCategory').map(([key,label])=>`<div class="field"><label for="batchMap-${key}">${esc(label)}</label><select id="batchMap-${key}" data-map="${key}"><option value="-1">Not mapped</option>${headers.map((h,i)=>blank(h)?'':`<option value="${i}" ${mapping[key]===i?'selected':''}>${esc(h)}</option>`).join('')}</select></div>`).join('');$('#batchMapping').hidden=false;await preview();}catch(e){status(e.message);$('#batchCommit').disabled=true;}}
 $('#batchSheet').onchange=()=>{sequence++;selectSheet();};$('#batchYear').onchange=preview;$('#batchApplyMapping').onclick=()=>{modal.querySelectorAll('[data-map]').forEach(el=>mapping[el.dataset.map]=+el.value);preview();};
 modal.addEventListener('change',e=>{if(e.target.matches('[data-map]')){sequence++;pending=[];$('#batchCommit').disabled=true;status('Mapping changed. Click Refresh preview before importing.');}});
 function dateValue(value){if(blank(value))return '';let y,m,d;if(typeof value==='number'){const parts=XLSX.SSF.parse_date_code(value,{date1904:!!workbook?.Workbook?.WBProps?.date1904});if(parts)({y,m,d}=parts);}else{let match=String(value).trim().match(/^(\d{4})-(\d{1,2})-(\d{1,2})(?:[T ].*)?$/);if(match)[,y,m,d]=match;else{match=String(value).trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(match)[,m,d,y]=match;}}
 if(!y||!m||!d)throw Error('Onset date must be an Excel date, YYYY-MM-DD or MM/DD/YYYY.');const date=new Date(Date.UTC(+y,+m-1,+d));if(date.getUTCFullYear()!==+y||date.getUTCMonth()!==+m-1||date.getUTCDate()!==+d)throw Error('Invalid onset date.');return date.toISOString().slice(0,10);}
 function choice(value,choices,label,fallback){if(blank(value)&&fallback!==undefined)return fallback;const result=choices[norm(value)];if(result===undefined)throw Error(`Invalid or missing ${label}.`);return result;}
 async function normalize(row){const get=key=>mapping[key]>=0?row[mapping[key]]:'';const rawId=String(get('id')??'').trim();if(!rawId)throw Error('Case ID is required.');const year=Number(blank(get('year'))?$('#batchYear').value:get('year')),mw=Number(get('mw'));if(!Number.isInteger(year)||year<1900||year>2100)throw Error('Invalid or missing year.');const maxWeek=context.disease==='dengue'&&year===2025?53:BinangonanReport.weeksInYear(year);if(!Number.isInteger(mw)||mw<1||mw>maxWeek)throw Error(`Morbidity week must be 1–${maxWeek}.`);
 if(!blank(get('disease'))){const disease=choice(get('disease'),{den:'dengue',dengue:'dengue',lep:'leptospirosis',lepto:'leptospirosis',leptospirosis:'leptospirosis'},'disease');if(disease!==context.disease)throw Error('Disease does not match the selected registry.');}
 const city=blank(get('city'))?'Binangonan':String(get('city')).trim();if(norm(city)!=='binangonan')throw Error('City / municipality must be Binangonan.');
 if(blank(get('age'))||!Number.isFinite(Number(get('age')))||Number(get('age'))<0||Number(get('age'))>120)throw Error('Age must be between 0 and 120.');
 let id=rawId;if(!context.cases.some(r=>r.id===rawId)&&!new RegExp(`^${context.disease==='dengue'?'DEN':'LEP'}-\\d{4}-[A-F0-9]{12}$`).test(rawId)){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(rawId));id=`${context.disease==='dengue'?'DEN':'LEP'}-${year}-`+[...new Uint8Array(bytes)].map(n=>n.toString(16).padStart(2,'0')).join('').slice(0,12).toUpperCase();}
 return {id,disease:context.disease,year,mw,onset:dateValue(get('onset')),age:Number(get('age')),sex:choice(get('sex'),{m:'Male',male:'Male',f:'Female',female:'Female',unknown:'Unknown'},'sex','Unknown'),
 classification:choice(get('classification'),{suspect:'Suspect',suspected:'Suspect',probable:'Probable',confirmed:'Confirmed'},'case classification'),outcome:choice(get('outcome'),{alive:'Alive',recovered:'Alive',died:'Died',dead:'Died',death:'Died'},'outcome'),
 city:'Binangonan',province:String(get('province')||'Rizal').trim(),barangay:String(get('barangay')||'Unknown').trim(),labResult:choice(get('labResult'),{positive:'Positive',negative:'Negative',pending:'Pending',unknown:'Unknown',nottested:'Not tested'},'laboratory result','Unknown'),testType:String(get('testType')||'Not specified').trim(),
 clinicalCategory:context.disease==='dengue'?choice(get('clinicalCategory'),{denguewithoutwarningsigns:'Dengue without warning signs',denguewithwarningsigns:'Dengue with warning signs',severedengue:'Severe dengue',notrecorded:'Not recorded'},'clinical category','Not recorded'):'',
 exposure:context.disease==='leptospirosis'?choice(get('exposure'),{floodrelated:'Flood related',mudexposure:'Mud Exposure',agriculturerelated:'Agriculture related',ingestionofcontaminatedfoodsdrinks:'Ingestion of contaminated foods/drinks',others:'Others',unknown:'Unknown'},'exposure','Unknown'):'Unknown',exposurePlace:context.disease==='leptospirosis'?String(get('exposurePlace')||'Unknown').trim():'Unknown'};
 }
 async function preview(){const seq=++sequence;pending=[];$('#batchCommit').disabled=true;$('#batchPreview').innerHTML='';if(!workbook)return;status('Checking records…');const issues=[],ready=[],ids=new Set(window.SurveillanceBatch.context().cases.map(r=>r.id));let duplicates=0,total=0;for(const key of ['id','mw','age','classification','outcome']){if(mapping[key]<0){status(`Map the ${fields.find(f=>f[0]===key)[1]} column, then refresh preview.`);return;}}
 for(let i=headerIndex+1;i<matrix.length;i++){if(seq!==sequence)return;const row=matrix[i];if(row.every(blank))continue;total++;try{const r=await normalize(row);if(ids.has(r.id)){duplicates++;continue;}ids.add(r.id);ready.push(r);}catch(e){issues.push({row:i+1,message:e.message});}if(i%200===0)await new Promise(resolve=>setTimeout(resolve,0));}
 if(seq!==sequence)return;pending=ready;status(`${total} rows checked · ${ready.length} ready to import · ${duplicates} duplicates skipped · ${issues.length} invalid rows skipped.`);
 $('#batchPreview').innerHTML=(issues.length?`<div class="batch-errors"><strong>Fix these rows in Excel and upload again, or import only the valid records below.</strong><ul>${issues.slice(0,40).map(i=>`<li>Row ${i.row}: ${esc(i.message)}</li>`).join('')}</ul>${issues.length>40?`<p>Showing the first 40 of ${issues.length} errors.</p>`:''}</div>`:'')+(ready.length?`<p>Preview: first ${Math.min(ready.length,40)} of ${ready.length} valid records. No changes have been saved yet.</p><div class="batch-table-wrap"><table class="data-table"><thead><tr><th>Case ID</th><th>Year / MW</th><th>Age / Sex</th><th>Barangay</th><th>Classification</th><th>Outcome</th></tr></thead><tbody>${ready.slice(0,40).map(r=>`<tr><td>${esc(r.id)}</td><td>${r.year} / ${r.mw}</td><td>${r.age} / ${esc(r.sex)}</td><td>${esc(r.barangay)}</td><td>${r.classification}</td><td>${r.outcome}</td></tr>`).join('')}</tbody></table></div>`:'');$('#batchCommit').textContent=`Import ${ready.length} valid records`;$('#batchCommit').disabled=!ready.length;
 }
 $('#batchCommit').onclick=()=>{try{if(!pending.length)return;const result=window.SurveillanceBatch.import(pending,context.disease);const count=result.added;close();$('#caseStatus').textContent=`Batch upload complete: ${count} cases added${result.skipped?`, ${result.skipped} duplicates skipped`:''}. `+$('#caseStatus').textContent;}catch(e){status('Import failed: '+e.message);}};
 $('#batchTemplate').onclick=()=>{const headers=['Case ID','Year','Morbidity Week','Date of Onset','Sex','Age in Years','Case Classification','Outcome','Barangay','City','Province','Laboratory Result','Type of Test Conducted',...(context.disease==='dengue'?['Clinical Category']:['Exposure','Place Exposure City Municipality'])];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([headers]),'Cases');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['Instructions'],['Fill in one case per row on the Cases sheet.'],['Required: Case ID, Year, Morbidity Week, Age in Years, Case Classification, Outcome.'],['Case Classification: Suspect, Probable, Confirmed. Outcome: Alive, Died.'],['Sex: Male, Female, Unknown. Age may include decimals for infants.'],['Dates: Excel dates, YYYY-MM-DD, or MM/DD/YYYY.'],['City must be Binangonan. Empty optional values remain unknown.'],['Matching Case IDs are skipped; existing records are not replaced.'],[context.disease==='dengue'?'Clinical Category: Dengue without warning signs, Dengue with warning signs, Severe dengue, Not recorded.':'Exposure: Flood related, Mud Exposure, Agriculture related, Ingestion of contaminated foods/drinks, Others, Unknown.'],['Do not include patient names, birth dates or street addresses.']]),'Instructions');XLSX.writeFile(book,`${context.disease}-batch-template.xlsx`);};
})();
