/* Additional dengue surveillance pages based on the supplied sample.pdf. */
(() => {
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=v=>String(v??'').trim().toLowerCase(),key=v=>norm(v).replace(/[^a-z0-9]/g,''),dead=r=>norm(r.outcome)==='died',pct=(n,d)=>d?(100*n/d).toFixed(2)+'%':'N/A',int=n=>Number(n).toLocaleString('en-US');
 const populationRows=[['Bangad',1503],['Batingan',16858],['Bilibiran',19229],['Binitagan',572],['Bombong',3385],['Buhangin',2063],['Calumpang',19773],['Ginoong Sanay',1793],['Gulod',1232],['Habagatan',1418],['Ithan',3886],['Janosa',3197],['Kalawaan',41084],['Kalinawan',2181],['Kasile',470],['Kaytome',2491],['Kinaboogan',1283],['Kinagatan',1505],['Libis',6115],['Limbon-limbon',1747],['Lunsad',12163],['Mahabang Parang',11441],['Macamot',10666],['Mambog',11768],['Palangoy',18499],['Pantok',17398],['Pila Pila',9773],['Pinagdilawan',815],['Pipindan',1987],['Rayap',2235],['Sapang',2331],['Tabon',617],['Tagpos',16560],['Tatala',16721],['Tayuman',12738],['Layunan',2677],['Libid',8352],['Malakaban',1157],['Pag-Asa',20169],['San Carlos',14595]];
 const storageKey='binangonan-dengue-details-v1';let preferences={};try{preferences=JSON.parse(localStorage.getItem(storageKey)||'{}');if(!preferences||Array.isArray(preferences))preferences={};}catch{}
 const populationFor=name=>{const n=preferences.population?.[key(name)];return n===null?null:Number.isFinite(+n)&&n!==''&&n!==undefined?+n:populationRows.find(r=>key(r[0])===key(name))?.[1]??null;};
 const populationSource=()=>preferences.populationSource||'Supplied sample.pdf; population reference year not stated.';
 const period=opt=>opt.period||BinangonanReport.periodLabel(opt.year,opt.end);
 const settingsKey=opt=>`${opt.year}:${opt.week}`;
 function stats(rows,prev,opt){
   const groups=new Map(populationRows.map(([name])=>[key(name),{name,population:populationFor(name),current:0,prior:0,deaths:0,priorDeaths:0,recent:0}]));
   for(const [records,isPrior] of [[rows,false],[prev,true]])for(const r of records){const name=String(r.barangay||'Unknown').trim()||'Unknown',k=key(name);if(!groups.has(k))groups.set(k,{name,population:populationFor(name),current:0,prior:0,deaths:0,priorDeaths:0,recent:0});const g=groups.get(k);g[isPrior?'prior':'current']++;g[isPrior?'priorDeaths':'deaths']+=dead(r)?1:0;if(!isPrior&&+r.mw>=Math.max(1,+opt.week-3)&&+r.mw<=+opt.week)g.recent++;}
   const barangays=[...groups.values()].map(g=>({...g,cluster:!['unknown','notspecified','na','unspecified'].includes(key(g.name))&&g.recent>=3}));
   const ages=rows.filter(r=>r.age!==''&&r.age!=null&&Number.isFinite(+r.age)&&+r.age>=0).map(r=>+r.age).sort((a,b)=>a-b),median=ages.length?(ages[Math.floor((ages.length-1)/2)]+ages[Math.floor(ages.length/2)])/2:null;
   const population=populationRows.reduce((sum,[name])=>sum+(populationFor(name)||0),0),populationComplete=populationRows.every(([name])=>populationFor(name)>0)&&barangays.every(g=>!g.current||g.population>0);
   return {rows,prev,barangays,ages,median,population,populationComplete,year:+opt.year,week:+opt.week,deaths:rows.filter(dead).length,priorDeaths:prev.filter(dead).length,male:rows.filter(r=>norm(r.sex)==='male').length,female:rows.filter(r=>norm(r.sex)==='female').length,notes:preferences.reports?.[settingsKey(opt)]||{}};
 }
 const ageText=a=>a<1?'<1':Number(a.toFixed(2)).toString();
 const range=s=>s.ages.length?`${ageText(s.ages[0])} to ${ageText(s.ages.at(-1))} years old`:'Not available';
 const change=(a,b)=>!b?(a?'N/A (prior 0)':'No change'):a===b?'No change':`${(100*Math.abs(a-b)/b).toFixed(2)}% ${a>b?'↑':'↓'}`;
 function summary(s,opt){const top=Math.max(0,...s.barangays.map(g=>g.current)),leaders=s.barangays.filter(g=>g.current===top&&top),lead=leaders.length===1?`Barangay ${esc(leaders[0].name)} has the highest number of cases: ${top} (${pct(top,s.rows.length)}).`:leaders.length?`${leaders.length} barangays share the highest count of ${top} cases each (${pct(top,s.rows.length)} each).`:'No cases were recorded for this period.';const sex=s.male===s.female?`Male and female case counts are equal (${s.male} each).`:`Most cases with recorded sex were ${s.male>s.female?'male':'female'} (${Math.max(s.male,s.female)}, ${pct(Math.max(s.male,s.female),s.rows.length)} of all cases).`;
   const comparison=s.prev.length?`${(100*Math.abs(s.rows.length-s.prev.length)/s.prev.length).toFixed(2)}% ${s.rows.length>=s.prev.length?'higher':'lower'} compared with the same morbidity weeks last year (${int(s.prev.length)} cases).`:'No prior-year cases are recorded for the same weeks; percent change is unavailable.';
   return `<ul class="dd-summary-list"><li>A total of <b>${int(s.rows.length)} dengue cases</b> with <b>${s.deaths} death${s.deaths===1?'':'s'}</b> (CFR: <b>${pct(s.deaths,s.rows.length)}</b>) were reported in Binangonan, Rizal from ${esc(period(opt))}. ${comparison}</li><li>${lead}</li><li>${s.rows.length?sex+' Ages range from <b>'+esc(range(s))+'</b>; median <b>'+(s.median==null?'not available':s.median)+' years</b>.':'Age and sex profile: no cases recorded.'}</li><li>Case classification: ${['Suspect','Probable','Confirmed'].map(label=>{const n=s.rows.filter(r=>norm(r.classification)===norm(label)).length;return `<b>${n} ${label.toLowerCase()}</b> (${pct(n,s.rows.length)})`;}).join('; ')}.</li></ul>`;
 }
 function comparisonTable(s){const row=g=>`<tr><td>${esc(g.name)}</td><td>${g.population==null?'N/A':int(g.population)}</td><td>${g.prior}</td><td>${g.priorDeaths}</td><td>${g.current}</td><td>${g.deaths}</td><td>${g.population>0?pct(g.current,g.population):'N/A'}</td><td>${pct(g.deaths,g.current)}</td><td>${pct(g.current,s.rows.length)}</td><td>${change(g.current,g.prior)}</td></tr>`;
   return `<table class="dd-comparison-table"><colgroup><col style="width:22%"><col style="width:11%"><col span="4" style="width:6%"><col span="3" style="width:9%"><col style="width:16%"></colgroup><thead><tr><th rowspan="2">Barangay</th><th rowspan="2">Population</th><th colspan="2">${s.year-1}</th><th colspan="2">${s.year}</th><th rowspan="2">Attack rate<br>(%)</th><th rowspan="2">CFR<br>(%)</th><th rowspan="2">Case<br>(%)</th><th rowspan="2">Change</th></tr><tr><th>Cases</th><th>Deaths</th><th>Cases</th><th>Deaths</th></tr></thead><tbody>${s.barangays.map(row).join('')}<tr class="dd-total"><td>TOTAL</td><td>${int(s.population)}</td><td>${s.prev.length}</td><td>${s.priorDeaths}</td><td>${s.rows.length}</td><td>${s.deaths}</td><td>${s.populationComplete?pct(s.rows.length,s.population):'N/A'}</td><td>${pct(s.deaths,s.rows.length)}</td><td>${s.rows.length?'100.00%':'N/A'}</td><td>${change(s.rows.length,s.prev.length)}</td></tr></tbody></table>`;
 }
 const populationNote=s=>`Population source: ${esc(populationSource())} Attack rate = cases / population × 100; CFR = deaths / cases × 100. Zero case denominators are shown as N/A.${s.populationComplete?'':' Municipal attack rate is unavailable where a population denominator is missing.'} Prior-year comparison uses the same morbidity weeks.`;
 function classifications(s){const table=(label,values,field)=>{const known=values.map(v=>norm(v)),extra=s.rows.filter(r=>!known.includes(norm(r[field]))).length;return `<tr class="dd-section-row"><th>${label}</th><th>No. of cases (%)</th></tr>${values.map(v=>{const n=s.rows.filter(r=>norm(r[field])===norm(v)).length;return `<tr><td>${esc(v)}</td><td>${n} (${pct(n,s.rows.length)})</td></tr>`;}).join('')}${extra?`<tr><td>Not recorded / other</td><td>${extra} (${pct(extra,s.rows.length)})</td></tr>`:''}`;};return `<table class="dd-classification"><tbody>${table('Case classification',['Suspect','Probable','Confirmed'],'classification')}${table('Clinical classification',['Dengue without warning signs','Dengue with warning signs','Severe dengue'],'clinicalCategory')}</tbody></table>`;}
 const profile=s=>`<table class="dd-profile"><thead><tr><th colspan="2">Profile of cases</th></tr></thead><tbody><tr><td>Age range</td><td>${esc(range(s))}</td></tr><tr><td>Median</td><td>${s.median==null?'Not available':s.median+' years old'}</td></tr></tbody></table>`;
 function clusters(s){const half=Math.ceil(s.barangays.length/2),part=items=>`<table class="dd-clusters"><tbody>${items.map(g=>`<tr><td>${esc(g.name)}</td><td class="${g.cluster?'dd-positive':''}">${g.cluster?'Possible cluster':key(g.name)==='unknown'?'Not assessed':'No clustering'} (${g.recent})</td></tr>`).join('')}</tbody></table>`;return `<div class="dd-cluster-columns">${part(s.barangays.slice(0,half))}${part(s.barangays.slice(half))}</div><p class="dd-note">Screening: at least 3 reported cases in a barangay during MW ${Math.max(1,s.week-3)}-${s.week}. Parentheses show the count in these 4 weeks. This is not an official hotspot declaration.</p>`;}
 const lines=value=>String(value||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean);
 const notesBlock=(title,value,blankCount)=>`<div class="dd-notes-group"><b>${title}</b>${lines(value).length?`<ol>${lines(value).map(v=>`<li>${esc(v)}</li>`).join('')}</ol>`:`<ol class="dd-blank-lines">${Array.from({length:blankCount},()=>'<li><span></span></li>').join('')}</ol>`}</div>`;
 const actions=s=>notesBlock('Municipal Health Office',s.notes.mho,3)+notesBlock('Municipal Epidemiology and Surveillance Unit (MESU)',s.notes.mesu,3)+notesBlock('Barangay',s.notes.barangay,3);
 const caption=(title,opt)=>`<div class="dd-caption">${esc(title)}<span>Binangonan, Rizal, as of ${esc(period(opt))}</span></div>`;
 function header(opt){return `<header class="dd-header"><img class="dd-wordmark" src="assets/binangonan-wordmark.png" alt="Mahal Kong Binangonan"><img src="assets/municipality.png" alt="Municipality of Binangonan"><div>Republic of the Philippines<strong>Municipality of Binangonan</strong>Municipal Health Office<b>Municipal Epidemiology and Surveillance Unit (MESU)</b></div><img src="assets/health-office.png" alt="Municipal Health Office"><img src="assets/surveillance.png" alt="Epidemiology and Surveillance Unit"></header><div class="dd-banner"><b>Epidemic-prone Diseases Case Surveillance (EDCS)<br>Weekly Dengue Surveillance Report</b><span>Morbidity Week<br>${esc(period(opt))}</span><strong>${opt.week}</strong></div>`;}
 function render(rows,prev,opt){const s=stats(rows,prev,opt);syncEditor(s,opt);return `<section class="dengue-detail-page" data-detail-page="1">${header(opt)}<h2 class="dd-summary-title">SUMMARY</h2><div class="dd-summary">${summary(s,opt)}</div><section class="dd-main-table">${caption(`Table 1. Distribution of Dengue Cases per Barangay (N=${s.rows.length})`,opt)}${comparisonTable(s)}</section><p class="dd-note">${populationNote(s)}</p><footer class="dd-page-footer">Binangonan Municipal Health Office · Figures are provisional and subject to validation. <span>Detailed report 1 of 2</span></footer></section><section class="dengue-detail-page" data-detail-page="2"><figure class="dd-weekly">${caption(`Figure 1. Dengue Cases by Morbidity Week, Alert and Epidemic Threshold (N=${s.rows.length})`,opt)}<div class="dd-chart">${BinangonanReport.charts.weekly(s.rows,opt.thresholds)}</div></figure><p class="dd-note dd-threshold-note">${esc(opt.thresholds?.note||'Historical baseline needed.')}</p><div class="dd-middle"><figure class="dd-age">${caption(`Figure 2. Dengue Cases by Sex and Age Group (N=${s.rows.length})`,opt)}<div class="dd-chart">${ageChart(s.rows)}</div></figure><section>${caption(`Table 2. Distribution by Case and Clinical Classification (N=${s.rows.length})`,opt)}${classifications(s)}${profile(s)}</section></div><div class="dd-bottom"><section>${caption(`Table 3. Possible Dengue Clustering per Barangay (N=${s.rows.length})`,opt)}${clusters(s)}</section><section class="dd-actions"><h2>Actions taken</h2>${actions(s)}</section></div><section class="dd-recommendations"><h2>Recommendations</h2>${notesBlock('',s.notes.recommendations,5)}</section><footer class="dd-page-footer">Source: local case registry · Counts and percentages use the selected reporting period. <span>Detailed report 2 of 2</span></footer></section>`;}
 function dashboard(rows,prev,opt){const s=stats(rows,prev,opt);return `<div class="dd-dashboard"><article class="dg-dashboard-card dd-wide"><span class="dg-eyebrow">DETAILED SURVEILLANCE SUMMARY</span><h2>Dengue report summary</h2>${summary(s,opt)}</article><article class="dg-dashboard-card dd-wide"><span class="dg-eyebrow">BARANGAY COMPARISON</span><h2>Population, cases, deaths, attack rate and case fatality rate</h2><p class="dg-card-period">MW 1-${s.week} · ${s.year-1} and ${s.year}</p><div class="dd-scroll">${comparisonTable(s)}</div><p class="dd-note">${populationNote(s)}</p></article><article class="dg-dashboard-card"><span class="dg-eyebrow">CASE & CLINICAL CLASSIFICATION</span><h2>Classification and age profile</h2>${classifications(s)}${profile(s)}</article><article class="dg-dashboard-card"><span class="dg-eyebrow">SEX & AGE GROUP</span><h2>Case counts by sex and age</h2><div class="dd-dashboard-age">${ageChart(s.rows)}</div></article><article class="dg-dashboard-card dd-wide"><span class="dg-eyebrow">POSSIBLE CLUSTERING</span><h2>Barangay screening through MW ${s.week}</h2>${clusters(s)}</article><article class="dg-dashboard-card dd-wide"><span class="dg-eyebrow">RESPONSE NOTES</span><h2>Actions taken and recommendations</h2><p class="dg-card-period">Enter the completed actions in Report & print → Detailed dengue report settings.</p><div class="dd-dashboard-actions">${actions(s)}${notesBlock('Recommendations',s.notes.recommendations,5)}</div></article></div>`;}
 const editor=document.createElement('details');editor.id='dengueDetailSettings';editor.className='report-signatory-controls dengue-detail-settings';document.querySelector('#reportPreview').before(editor);let editorPeriod='';
 function syncEditor(s,opt){const id=settingsKey(opt);if(id===editorPeriod&&editor.innerHTML)return;editorPeriod=id;editor.innerHTML=`<summary>Detailed dengue report settings · ${s.year} / MW ${s.week}</summary><p>Actions and recommendations are saved for this reporting year and week. Enter one item per line: up to 3 short actions per office (240 characters), and 5 recommendations (400 characters).</p><div class="dd-editor-notes">${[['mho','Municipal Health Office'],['mesu','Municipal Epidemiology and Surveillance Unit'],['barangay','Barangay'],['recommendations','Recommendations']].map(([k,label])=>`<div class="field"><label for="dd-${k}">${label}</label><textarea id="dd-${k}" data-note="${k}" rows="4" maxlength="${k==='recommendations'?400:240}" placeholder="Enter actual actions or recommendations">${esc(s.notes[k]||'')}</textarea></div>`).join('')}</div><details><summary>Barangay population reference</summary><p>Used only to calculate attack rate. Keep the reference source and year accurate.</p><div class="field"><label for="ddPopulationSource">Source / reference year</label><input id="ddPopulationSource" maxlength="180" value="${esc(populationSource())}"></div><div class="dd-population-editor">${populationRows.map(([name])=>`<div class="field"><label>${esc(name)}</label><input data-population="${key(name)}" type="number" min="0" step="1" max="10000000" value="${populationFor(name)??''}"></div>`).join('')}</div></details><button class="btn primary" id="ddSaveSettings" type="button">Save detailed report settings</button><span id="ddSettingsFeedback" role="status"></span>`;
 document.querySelector('#ddSaveSettings').onclick=()=>{try{const population={},notes={};editor.querySelectorAll('[data-population]').forEach(el=>{if(!el.checkValidity())throw Error('Population must be a whole number of 0 or more.');population[el.dataset.population]=el.value===''?null:Number(el.value);});editor.querySelectorAll('[data-note]').forEach(el=>{const limit=el.dataset.note==='recommendations'?400:240,itemLimit=el.dataset.note==='recommendations'?5:3;if(el.value.length>limit||lines(el.value).length>itemLimit)throw Error(`Use up to ${itemLimit} items and ${limit} characters for ${el.dataset.note}.`);notes[el.dataset.note]=el.value;});const next={...preferences,population,populationSource:document.querySelector('#ddPopulationSource').value.trim(),reports:{...preferences.reports,[id]:notes}};localStorage.setItem(storageKey,JSON.stringify(next));preferences=next;document.dispatchEvent(new Event('dengue-details-updated'));document.querySelector('#ddSettingsFeedback').textContent='Saved. Dashboard and printable pages updated.';}catch(error){document.querySelector('#ddSettingsFeedback').textContent=error.message;}};
 }
function ageChart(rows){
 const groups=['>60','51-60','41-50','31-40','21-30','11-20','1-10','<1'],bucket=age=>age<1?'<1':age<=10?'1-10':age<=20?'11-20':age<=30?'21-30':age<=40?'31-40':age<=50?'41-50':age<=60?'51-60':'>60';
 const valid=rows.filter(row=>row.age!==''&&row.age!=null&&Number.isFinite(+row.age)&&+row.age>=0&&['male','female'].includes(norm(row.sex)));
 const values=groups.map(group=>({group,male:valid.filter(row=>bucket(+row.age)===group&&norm(row.sex)==='male').length,female:valid.filter(row=>bucket(+row.age)===group&&norm(row.sex)==='female').length}));
 const peak=Math.max(1,...values.flatMap(value=>[value.male,value.female])),step=peak<=5?1:peak<=20?5:peak<=60?10:peak<=150?25:Math.ceil(peak/5/50)*50,bound=Math.ceil(peak/step)*step;
 const width=420,height=285,left=58,right=16,top=17,bottom=50,center=left+(width-left-right)/2,unit=(width-left-right)/2/bound,rowHeight=(height-top-bottom)/8;
 let body='';for(let tick=-bound;tick<=bound;tick+=step){const x=center+tick*unit;body+=`<line x1="${x}" y1="${top}" x2="${x}" y2="${height-bottom}" stroke="${tick===0?'#6885a0':'#e2ebf3'}" stroke-width=".7"/><text x="${x}" y="${height-bottom+16}" text-anchor="middle" font-size="10">${Math.abs(tick)}</text>`;}
 values.forEach((value,index)=>{const y=top+index*rowHeight;body+=`<text x="${left-8}" y="${y+rowHeight/2+4}" text-anchor="end" font-size="11">${value.group}</text><rect x="${center-value.male*unit}" y="${y+2}" width="${value.male*unit}" height="${rowHeight-4}" fill="#145b98"/><rect x="${center}" y="${y+2}" width="${value.female*unit}" height="${rowHeight-4}" fill="#83b6e2"/>`;});
 body+=`<text x="${center}" y="${height-18}" text-anchor="middle" font-size="10">Number of cases</text><rect x="158" y="276" width="7" height="7" fill="#145b98"/><text x="169" y="283" font-size="10">Male</text><rect x="220" y="276" width="7" height="7" fill="#83b6e2"/><text x="231" y="283" font-size="10">Female</text>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="Dengue case counts by sex and age group" style="font-family:Arial,sans-serif;fill:#163e65"><title>${valid.length} cases with known age and sex; ${rows.length-valid.length} excluded</title>${body}</svg>`;
 }
 const originalRender=DengueReport.render,originalDashboard=DengueReport.dashboard;
 DengueReport.render=(all,opt)=>{const s=BinangonanReport.stats(all,+opt.year,+opt.week);return originalRender(all,opt)+render(s.rows,s.prev,opt);};
 DengueReport.dashboard=(rows,prev,opt)=>originalDashboard(rows,prev,opt)+dashboard(rows,prev,opt);
 window.DengueDetails={stats,populationRows};
})();
